### ISSUE TITLE
Get rid of python code

### ISSUE THREAD

**Issue by katzper-michno** [km1chno/overleaf-sync-rs#21]
To accomplish this, we need a socket.io client that is able to communicate with V2 version of Socket.io protocol. As far as I know, there is no such client for Rust.

https://github.com/1c3t3a/rust-socketio supports only V4 and V5. There is an open issue https://github.com/1c3t3a/rust-socketio/issues/132, but it doesn't seem to get a lot of traction.

Our client is pretty trivial, we only need to connect, wait for one specific event and disconnect, so maybe implementing the protocol in this limited scope is feasible. We can also choose only one way of transport, we don't need both websockets and polling.

**Comment by sunnysab** [comment]
Hello! Does overleaf use v2 version of socket.io? I see that in the open-source version of the overleaf, they are using an old forked version! (
0.9.19-overleaf-10) (https://github.com/overleaf/socket.io)

By the way, code in client.py doesn't work now. Do you know if there was something changed in overleaf? Thank you!

```shell
Traceback (most recent call last):
  File "/home/sunnysab/Projects/dont-push/web.py", line 52, in <module>
    main()
  File "/home/sunnysab/Projects/dont-push/web.py", line 31, in main
    socket_io = SocketIO(BASE_URL,
                ^^^^^^^^^^^^^^^^^^
  File "/home/sunnysab/Projects/dont-push/.venv/lib/python3.12/site-packages/socketIO_client/__init__.py", line 351, in __init__
    super(SocketIO, self).__init__(
  File "/home/sunnysab/Projects/dont-push/.venv/lib/python3.12/site-packages/socketIO_client/__init__.py", line 54, in __init__
    self._transport
  File "/home/sunnysab/Projects/dont-push/.venv/lib/python3.12/site-packages/socketIO_client/__init__.py", line 62, in _transport
    self._engineIO_session = self._get_engineIO_session()
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sunnysab/Projects/dont-push/.venv/lib/python3.12/site-packages/socketIO_client/__init__.py", line 75, in _get_engineIO_session
    engineIO_packet_type, engineIO_packet_data = next(
                                                 ^^^^^
StopIteration
```

**Comment by katzper-michno** [comment]
Hi! `socket.io` semantic versioning is a bit confusing, in [SocketIO V3 protocol docs](https://github.com/socketio/socket.io-protocol/tree/v3) you can see that `socketio@1.0.0` uses V3, while V1 and V2 were never included in official release. That's why I believe the version `0.9.19` that Overleaf uses implements V2.

I tested `client.py` today and it is working for me, so perhaps there were no recent changes in Overleaf interface. 

Are you sure you provide all three necessary parameters properly? (`GLCB` and `overleaf_session_2` cookies, and `project_id`) 

You can obtain the cookies with the script by running `olsync login` and checking `~/.olsyncinfo`, the `project_id` can be found with `cat project_dir/.olsync/projectinfo` after `olsync pull` or in Overleaf from url after opening the project

**Comment by sunnysab** [comment]
> Hi! `socket.io` semantic versioning is a bit confusing, in [SocketIO V3 protocol docs](https://github.com/socketio/socket.io-protocol/tree/v3) you can see that `socketio@1.0.0` uses V3, while V1 and V2 were never included in official release. That's why I believe the version `0.9.19` that Overleaf uses implements V2.
> 
> I tested `client.py` today and it is working for me, so perhaps there were no recent changes in Overleaf interface.
> 
> Are you sure you provide all three necessary parameters properly? (`GLCB` and `overleaf_session_2` cookies, and `project_id`)
> 
> You can obtain the cookies with the script by running `olsync login` and checking `~/.olsyncinfo`, the `project_id` can be found with `cat project_dir/.olsync/projectinfo` after `olsync pull` or in Overleaf from url after opening the project

Thank you!
I've set logging level to DEBUG and see the URL that socketIO_client get is wrong, so I run:
```shell
pip install socketIO-client==0.5.7.4
```
and all are well.
